name: persona_app
services:
  maria_db:
    container_name: maria_db
    image: mariadb:11.4
    environment:
      MARIADB_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - maria_db_data:/var/lib/mysql
      - ./scripts/persona_ddl_maria.sql:/docker-entrypoint-initdb.d/persona_ddl_maria.sql
      - ./scripts/persona_dml_maria.sql:/docker-entrypoint-initdb.d/persona_dml_maria.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo_db:
    container_name: mongo_db
    image: mongodb/mongodb-community-server:8.0.3-ubuntu2204
    environment:
      MONGODB_INITDB_ROOT_USERNAME: persona_db
      MONGODB_INITDB_ROOT_PASSWORD: persona_db
      MONGODB_INITDB_DATABASE: persona_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_db_data:/data/db
      - ./scripts/persona_ddl_mongo.js:/docker-entrypoint-initdb.d/persona_ddl_mongo.js
      - ./scripts/persona_dml_mongo.js:/docker-entrypoint-initdb.d/persona_dml_mongo.js
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  rest_api:
    container_name: rest_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - maria_db
      - mongo_db
    environment:
      MARIA_DB_HOST: maria_db
      MARIA_DB_PORT: 3306
      MONGO_DB_HOST: mongo_db
      MONGO_DB_PORT: 27017

volumes:
  maria_db_data:
  mongo_db_data:

networks:
  default:
    driver: bridge